name: astra
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  analyzer: ^9.0.0
  args: ^2.7.0
  build: ^4.0.3
  macros: ^0.0.1
  meta: ^1.10.0
  shelf: ^1.4.0
  source_gen: ^4.1.1
  watcher: ^1.2.1
  # Modules
  dart_jsonwebtoken: ^2.12.0
  logging: ^1.2.0
  # Database
  drift: ^2.24.0
  drift_postgres: ^1.3.1
  postgres: ^3.4.0
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  http: ^1.6.0

dev_dependencies:
  build_runner: ^2.4.0
  drift_dev: ^2.24.0
  lints: ^6.0.0
  test: ^1.25.6
